services:
  # Backend API Service
  - type: web
    name: elite-barber-shop-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: elite-barber-shop-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_FROM
        value: Elite Barber Shop <noreply@elitebarbershop.com>
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: elite-barber-shop-web
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VUE_APP_API_URL
        value: https://elite-barber-shop-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: elite-barber-shop-db
    databaseName: barber_shop
    user: barber_shop_user
    plan: starter
